name: daily_tasks_v3
description: A simple to-do app to keep your daily tasks in on place. Created using Flutter & Dart.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  google_fonts: ^2.3.1
  get: ^4.6.1
  flutter_slidable: ^1.2.0
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  file_picker_cross: ^4.5.0
  path_provider: ^2.0.9


dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#    - assets/videos/
#    - assets/audios/
#    - assets/lottie_animations/
#    - assets/rive_animations/
#    - assets/pdfs/
